# .github/workflows/chromatic.yml

name: 'Chromatic - Ui tests'

on:
  pull_request:
    branches:
      - master
      - beta
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  chromatic-deployment:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history
      - name: Install dependencies
        run: npm ci
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Options required to the GitHub Chromatic Action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: 'npm run storybook:build'
          exitZeroOnChanges: true # 👈 Option to prevent the workflow from failing
