name: Run CI checks

on:
  pull_request:
    branches:
      - 'master'
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  unit-tests:
    name: Run Unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install dependencies
      run: npm ci
    - name: Run linter
      run: npm run lint
    - name: Run tests
      run: npm run test
