name: Publish NPM package
on:
  push:
    branches:
      - master
      - beta

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      id: semantic
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
